name: Development CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ '**', '!master', '!development' ]
  pull_request:
    branches: '**'
    # branches: [ '**', '!master', '!development' ]

#   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLUTTER_VERSION: '2.2.2' 

jobs:
  build:
    name: Build & Test
    # environment: Development
    runs-on: ubuntu-latest

    steps:
      # Get Code     
      - uses: actions/checkout@v2

      # - uses: actions/setup-java@v1 # Setup Java environment in order to build the Android app.
      #   with:
      #     java-version: '12.x'
      
      - name: Use Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', 'beta', default to: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}
      
      # Get flutter dependencies.
      - run: flutter pub get
      
      # # Check for any formatting issues in the code.
      # - run: flutter format --set-exit-if-changed .
      
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
      
      # Run widget tests for our flutter project.
      - run: flutter test
      
      # Build web version.
      - run: flutter build web --release